# Generated by Django 3.1.1 on 2020-09-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('MI', 'Mumbai Indians'), ('CSK', 'Chennai Super Kings'), ('RCB', 'Royal Challengers Banglore'), ('RR', 'Rajasthan Royals'), ('DC', 'Delhi Capitals'), ('SRH', 'Sunrisers Hyderabad'), ('KXIP', 'Kings XI Punjab'), ('KKR', 'Kolkata Knight Riders')], default='MI', max_length=20)),
            ],
        ),
    ]
